### ISSUE TITLE
Getting error with 11clicks on M1 Mac Sillicon 

### ISSUE THREAD

**Issue by koshimazaki** [11ols/11clicks#1]
Hey this is awesome external. I wanted to use it to automate recording with Syphon. 

Max doesn't want to recognise it for some reason for me. Help file works fine.
Getting this in Max console:

_11clicks: unable to load extern, object has no function named 'ext_main' or 'main'_

Im using this version: 11clicks_2022_01_17
Would you have an idea whats wrong? It flagged it as Mac OS quarantine.

**Comment by 11ols** [comment]
Ok, interessting. I'll look into it.

**Comment by 11ols** [comment]
Regarding the quarantine Max should ask: 
"Max can attept to remove quarantine attributes from 11clicks.mxo."
"Proceed?"
Have you seen this message?

**Comment by 11ols** [comment]
Could you test this version if it makes any difference
[11clicks.mxo.zip](https://github.com/11ols/11clicks/files/7964482/11clicks.mxo.zip)
?

**Comment by koshimazaki** [comment]
It works! thanks a lot for such quick response. 
I still get Max quarantine warning message, but looks like Max is sorting the flags out. 
Thank you! This is really useful object great for hacking the operating system :)

**Comment by 11ols** [comment]
Ok, nice. Thanks for the report.
